web:
  image: node:5.5-slim
  container_name: web
  ports:
    - "80:3000"
    - "9485:9485"
  links:
    - db:database
  volumes:
    - .:/docker
  working_dir: /docker
  command: npm start
db:
  image: mongo:3.2
  container_name: db
