web:
  container_name: web
  image: node:5.5-slim
  ports:
    - "80:3000"
    - "9486:9486" # autoreload
  links:
    - db:database
  volumes:
    - .:/docker
  working_dir: /docker
  command: npm start
db:
  container_name: db
  image: mongo:3.2
